.\"
.\" This file and its contents are supplied under the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" http://www.illumos.org/license/CDDL.
.\"
.\"
.\" Copyright 2019 Joyent, Inc.
.\"
.Dd February 18, 2019
.Dt XXX 3CTF
.Os
.Sh NAME
.Nm ctf_xxxx
.Nd xxx
.Sh SYNOPSIS
.Lb libctf
.In libctf.h
.Sh DESCRIPTION
.Sh RETURN VALUES
.Sh ERRORS
.Sh INTERFACE STABILITY
.Sy Private
.Sh MT-LEVEL
See
.Sy LOCKING
in
.Xr libctf 3LIB .
.Sh SEE ALSO
.Xr libctf 3LIB
